config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'

   }
   resource :user, only: %i[edit] do
    collection do
      patch 'update_password'
    end
  end

  root 'posts#index'

  get '/users/:id', to: 'users#show', as: 'user'

  get 'posts/search', to: 'posts#search', as: 'search'

  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :posts, only: %i(index new create show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
    resources :bookmarks, only: %i[create destroy]
  end

   resources :relationships,       only: [:create, :destroy]
   resources :notifications,       only: [:index, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes
  has_many :comments
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship",
                                  foreign_key: "followed_id",
                                  dependent: :destroy
  has_many :active_notifications, foreign_key:"visitor_id",
                                  class_name: "Notification",
                                  dependent: :destroy
  has_many :passive_notifications, foreign_key:"visited_id",
                                   class_name: "Notification",
                                   dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :bookmarks, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  validates :username, uniqueness: true


  def update_without_current_password(params, *options)
    params.delete(:current_password)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end
    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def create_notification_follow!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and action = ? ",current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.includes(:photos).order('created_at DESC')
  end

  def following
    @title = "フォロー中のユーザー"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  def edit
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update_with_password(user_params)
      bypass_sign_in(@user)
      flash[:notice] = "パスワードが変更されました"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "変更に失敗しました"
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end

end

app/views/users/_user.html.erb
<li>
  <%= image_tag avatar_url(@user), class: "round-img-for-list" %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Password Change") %>

<div class="main">
  <div class="devise-outer">
    <div class="form-wrap">
      <%= form_with model:@user, url: update_password_user_path, method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :current_password, "現在のパスワード" %>
          <%= f.password_field :current_password, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password, "新しいパスワード" %>
          <%= f.password_field :password, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "新しいパスワードの確認" %>
          <%= f.password_field :password_confirmation, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group text-center">
          <%= f.submit "変更する", class: "btn btn-primary" %>
        </div>
      <% end %>
      <br>
      <p><%= link_to "戻る", user_path(@user) %></p>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile-wrap">
  <div class="row">
    <div class="col-md-4 text-center">
      <%= image_tag avatar_url(@user), class: "round-img" %>
    </div>
    <div class="col-md-8">
      <div class="row">

        <h1><%= @user.username %></h1>
        <% if @user == current_user %>
          <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark edit-profile-btn" %>
          <button type="button" class="setting" data-toggle="modal" data-target="#exampleModal"></button>
        <% else %>
          <%= render 'partial/follow_form' %>
        <% end %>
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">×</span>
                </button>
              </div>
              <div class="list-group text-center">
                <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                <%= link_to "パスワードを変更", edit_user_path, method: :get,class: "list-group-item list-group-item-action" %>
                <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <p>フルネーム：<%= @user.name %>
          <br>ウェブサイト：<%= @user.website %>
          <br>自己紹介：<%= @user.self_intro %>
        </p>
      </div>
      <div class="row stats">
        <h6>
          <%= render 'partial/stats' %>
        </h6>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <%= render "posts/card-list", {posts: @posts}%>
  </div>
</div>

app/views/users/show_follow.html.erb
<div class="profile-wrap">
  <% provide(:title, @title) %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= image_tag avatar_url(@user), class: "round-img" %>
        <h1><%= @user.name %></h1>
        <span><%= link_to "プロフィール", @user %></span>
        <span><b>投稿:</b> <%= @user.posts.count %></span>
      </section>
      <section class="stats">
        <%= render 'partial/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3><%= @title %></h3>
      <% if @users.any? %>
        <ul class="users follow">
          <%= render @users %>
        </ul>
      <% end %>
    </div>
  </div>
</div>