config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'

   }
   resource :user, only: %i[edit] do
    collection do
      patch 'update_password'
    end
  end

  root 'posts#index'

  get '/users/:id', to: 'users#show', as: 'user'

  get 'posts/search', to: 'posts#search', as: 'search'

  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :posts, only: %i(index new create show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
    resources :bookmarks, only: %i[create destroy]
  end

   resources :relationships,       only: [:create, :destroy]
   resources :notifications,       only: [:index, :destroy]
end

app/views/partial/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/partial/_follow_form.html.erb
  <div id="follow_form" class= "col-md-2 offset-md-0.5">
  <% if current_user.following?(@user) %>
    <%= render 'partial/unfollow' %>
  <% else %>
    <%= render 'partial/follow' %>
  <% end %>
  </div>

app/views/partial/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center">
      <p>
        insta_clone
      </p>
    </div>
  </div>
</footer>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <%= link_to "", root_path, class: "navbar__brand navbar__mainLogo" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-md-auto align-items-center">
        <li>
          <%= search_form_for @search, url: search_path do |f| %>
            <form class="form-inline" style="display: inline">
              <%= f.search_field :caption_cont, class: "mr-sm-4 col-md-6",placeholder: "キャプション検索", autocomplete: :on  %>
              <%= f.submit "検索", class: "btn btn-primary my-2 my-sm-0" %>
            </form>
          <% end %>
        </li>
        <li>
          <% if unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: red;"></i>
          <% end %>
              <%= link_to "", notifications_path, class: "far fa-bell fa-3x" %>
        </li>
        <li>
           <%= link_to "投稿", new_post_path, class: "btn btn-primary" %>
        </li>
        <li>
          <%= link_to "", user_path(current_user), class: "nav-link commonNavIcon profile-icon" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/partial/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a>投稿 <span class="font-weight-bold"><%= @user.posts.count %></span>件</a>
  <a href="<%= following_user_path(@user) %>">
    フォロー数：
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
  </a>
  <a href="<%= followers_user_path(@user) %>">
    フォロワー数：
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
  </a>
</div>

app/views/partial/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>