config/routes.rb
Rails.application.routes.draw do

  get 'bookmarks/create'
  get 'bookmarks/destroy'
  devise_for :users, :controllers => {
    :registrations => 'users/registrations'

   }
   resource :user, only: %i[edit] do
    collection do
      patch 'update_password'
    end
  end

  root 'posts#index'

  get '/users/:id', to: 'users#show', as: 'user'

  get 'posts/search', to: 'posts#search', as: 'search'

  resources :users do
    member do
      get :following,:followers
    end
  end

  resources :posts, only: %i(index new create show destroy) do
    resources :photos, only: %i(create)
    resources :likes, only: %i(create destroy)
    resources :comments, only: %i(create destroy)
    resources :bookmarks, only: %i[create destroy]
  end

   resources :relationships,       only: [:create, :destroy]
   resources :notifications,       only: [:index, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :notifications, dependent: :destroy
  accepts_nested_attributes_for :photos

  def liked_by(current_user)
    Like.find_by(user_id: current_user.id, post_id: id)
  end

  def bookmarked_by?(current_user)
    Bookmark.find_by(user_id: user.id, post_id: id)
  end

  def create_notification_like!(current_user)
    temp = Notification.where(["visitor_id = ? and visited_id = ? and post_id = ? and action = ? ",
                                  current_user.id, user_id, id, 'like'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )

      if notification.visitor_id == notification.visited_id
         notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  def create_notification_comment!(current_user, comment_id)
    temp_ids = Comment.where(post_id: id).where.not("user_id=? or user_id=?", current_user.id,user_id).select(:user_id).distinct
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
    save_notification_comment!(current_user, comment_id, user_id)
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
      notification = current_user.active_notifications.new(
        post_id: id,
        comment_id: comment_id,
        visited_id: visited_id,
        action: 'comment'
      )
      if notification.visitor_id == notification.visited_id
        notification.checked = true
      end
      notification.save if notification.valid?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = Post.new
    @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      redirect_to root_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to root_path
      flash[:alert] = "投稿に失敗しました"
    end
  end

  def index
    @posts = Post.limit(10).includes(:photos, :user).order('created_at DESC')
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    if @post.user == current_user
      flash[:notice] = "投稿が削除されました" if @post.destroy
    else
      flash[:alert] = "投稿の削除に失敗しました"
    end
    redirect_to root_path
  end

  def search
    @posts = @search_posts.page(params[:page]).per(9)
  end

  private
    def post_params
      params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
    end
end

app/views/posts/_card-list.html.erb
<% @posts.each do |post| %>

  <div class="col-md-4  mx-auto array">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>
        </div>
        <%= link_to(post_path(post)) do %>
          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <% end %>
        <div class="card-body">
             <div id="comment-post-<%= post.id.to_s %>">
               <%= render 'posts/comment_list', { post: post } %>
             </div>
             <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
               class: "light-color post-time no-text-decoration" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

  <div class="col-md-4  mx-auto array">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <%= image_tag avatar_url(post.user), class: "post-profile-icon" %>
          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>
          <% if post.user_id == current_user.id %>
            <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
              <div class="delete-post-icon">
              </div>
            <% end %>
          <% end %>
        </div>
        <%= link_to(post_path(post)) do %>
          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <div class="row parts">
            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", post_like_path(post.id, post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>
            <div id="bookmark-icon-post-<%= post.id.to_s %>", class="ml-2" >
              <% if post.bookmarked_by?(current_user).present? %>
                <%= link_to "ブックマークを取り消す", post_bookmark_path(post.id, post.bookmarked_by?(current_user)), method: :DELETE, remote: true, class: "bookmarked hide-text"%>
              <% else %>
                <%= link_to "ブックマーク", post_bookmarks_path(post), method: :POST, remote: true, class: "bookmark hide-text" %>
              <% end %>
            </div>
            <%= link_to "", "#", class: "comment" %>
          </div>
          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>
          <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
             <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>
          <div id="comment-post-<%= post.id.to_s %>">
            <%= render 'comment_list', { post: post } %>
          </div>
          <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
            class: "light-color post-time no-text-decoration" %>
          <hr>
          <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
            <%= form_with model: [post, Comment.new], class: "w-100" do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :post_id, value: post.id %>
              <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
            <% end %>
          </div>
         </div>
       </div>
     </div>
   </div>
 </div>
<% end %>

app/views/posts/new.html.erb
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_with model: @post, class: "upload-images p-0 border-0" do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
              <%= image_tag avatar_url(current_user), class: "post-profile-icon" %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "キャプションを書く" %>
            </div>
          </div>
          <div class="mb-3">

            <%= f.fields_for :photos do |i| %>
              <%= i.file_field :image %>
            <% end %>

          </div>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<% provide(:title, "Search Result") %>

<div class="container">
  <h4 class="text-center titlespace">検索結果</h4>
  <div class="content-center mt-5">
    <%= paginate @posts %>
  </div>
  <div class="row">
    <%= render "posts/card-list", {posts: @posts}%>
  </div>
</div>

app/views/posts/show.html.erb
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <%= image_tag avatar_url(@post.user), class: "post-profile-icon" %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration post-user-name",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>
            <% if @post.user_id == current_user.id %>
              <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon">
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="m-2">
            <strong>
              <%= @post.caption %>
            </strong>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
              <div id="comment-post-<%= @post.id.to_s %>">
                <%= render 'comment_list', post: @post %>
              </div>
            </div>
          </div>
        </div>
        <div class="row parts">
          <div id="like-icon-post-<%= @post.id.to_s %>">
            <% if @post.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", post_like_path(@post.id, @post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
            <% end %>
          </div>
          <div id="bookmark-icon-post-<%= @post.id.to_s %>", class="ml-2" >
            <% if @post.bookmarked_by?(current_user).present? %>
              <%= link_to "ブックマークを取り消す", post_bookmark_path(@post.id, @post.bookmarked_by?(current_user)), method: :DELETE, remote: true, class: "bookmarked hide-text"%>
            <% else %>
              <%= link_to "ブックマーク", post_bookmarks_path(@post), method: :POST, remote: true, class: "bookmark hide-text" %>
            <% end %>
          </div>
        </div>
        <div id="like-text-post-<%= @post.id.to_s %>">
          <%= render "like_text", { likes: @post.likes } %>
        </div>
        <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>
        <div class="row parts" id="comment-form-post-<%= @post.id.to_s %>">
          <%= form_with model: [@post, Comment.new],  class: "w-100" do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>